wordpress:
 build: wordpress/
 container_name: wordpress
 ports:
   - "8081:80"
 links:
   - db:redis
 external_links:
   - logstash
 log_driver: syslog
 log_opt:
   syslog-address: "tcp://logstash-ip:25826"

db:
  build: redis/
  container_name: redis
  ports:
    - "6379:6379"
  volumes:
    - /srv/docker/redis:/var/lib/redis
  restart: always
