---

- name: Configure EC2 instance
  hosts: local
  remote_user: ubuntu
  connection: local
  sudo: true


  tasks:
  - name: Removing previous docker 
    command: apt-get remove docker docker-engine -y

  - name: Update the machine
    command: apt-get update -y
    
  - name: Installing essentials
    command: apt-get install apt-transport-https ca-certificates curl software-properties-common -y
      
  - name: Installing Curl
    command: apt-get install curl -y
      
  - name: Update the machine
    command: apt-get update
  
  - name: Installing docker
    command: apt-get install -y docker.io

  - name: Update the machine2
    command: apt-get update

  - name: Adding user to group
    command: usermod -aG docker ${USER}

  - name: Switching user to root
    command: su -
    
  - name: Installing Pip
    command: apt install python-pip -y

  - name: Installing Docker Compose
    command: sudo pip install docker-compose
      
  - name: Making executable
    command: chmod +x /usr/local/bin/docker-compose
    
