---

- name: Configure EC2 instance
  hosts: ec2
  connection: ssh
  sudo: true


  tasks:
  - name: Update the machine
    command: sudo apt-get clean && update -y
    
  - name: Installing essentials
    command: apt-get install apt-transport-https ca-certificates curl software-properties-common -y
      
  - name: Installing Curl
    command: apt-get install curl -y
  
  - name: Installing docker
    command: apt install docker.io -y

  - name: Adding user to group
    command: sudo usermod -aG docker ${USER}

  - name: Restarting docker service
    command: sudo service docker restart 

  - name: Switching user to root
    command: su -

  - name: Installing Docker Compose
    command: sudo apt install docker-compose -y

  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    sudo: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    sudo: yes
    when: apt_result|failed
    
